// Code generated by "stringer -type=EthP -trimprefix=ETH_P_ ethp.go"; DO NOT EDIT.

package xeth

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ETH_P_1588-35063]
	_ = x[ETH_P_8021Q-33024]
	_ = x[ETH_P_8021AD-34984]
	_ = x[ETH_P_802_2-4]
	_ = x[ETH_P_802_3-1]
	_ = x[ETH_P_AARP-33011]
	_ = x[ETH_P_ALL-3]
	_ = x[ETH_P_AOE-34978]
	_ = x[ETH_P_ARCNET-26]
	_ = x[ETH_P_ARP-2054]
	_ = x[ETH_P_ATALK-32923]
	_ = x[ETH_P_ATMFATE-34948]
	_ = x[ETH_P_ATMMPOA-34892]
	_ = x[ETH_P_AX25-2]
	_ = x[ETH_P_BPQ-2303]
	_ = x[ETH_P_CAIF-247]
	_ = x[ETH_P_CAN-12]
	_ = x[ETH_P_CONTROL-22]
	_ = x[ETH_P_CUST-24582]
	_ = x[ETH_P_DDCMP-6]
	_ = x[ETH_P_DEC-24576]
	_ = x[ETH_P_DIAG-24581]
	_ = x[ETH_P_DNA_DL-24577]
	_ = x[ETH_P_DNA_RC-24578]
	_ = x[ETH_P_DNA_RT-24579]
	_ = x[ETH_P_DSA-27]
	_ = x[ETH_P_ECONET-24]
	_ = x[ETH_P_EDSA-56026]
	_ = x[ETH_P_FCOE-35078]
	_ = x[ETH_P_FIP-35092]
	_ = x[ETH_P_HDLC-25]
	_ = x[ETH_P_IEEE802154-246]
	_ = x[ETH_P_IEEEPUP-2560]
	_ = x[ETH_P_IEEEPUPAT-2561]
	_ = x[ETH_P_IP-2048]
	_ = x[ETH_P_IPV6-34525]
	_ = x[ETH_P_IPX-33079]
	_ = x[ETH_P_IRDA-23]
	_ = x[ETH_P_LAT-24580]
	_ = x[ETH_P_LINK_CTL-34924]
	_ = x[ETH_P_LOCALTALK-9]
	_ = x[ETH_P_LOOP-96]
	_ = x[ETH_P_MOBITEX-21]
	_ = x[ETH_P_MPLS_MC-34888]
	_ = x[ETH_P_MPLS_UC-34887]
	_ = x[ETH_P_PAE-34958]
	_ = x[ETH_P_PAUSE-34824]
	_ = x[ETH_P_PHONET-245]
	_ = x[ETH_P_PPPTALK-16]
	_ = x[ETH_P_PPP_DISC-34915]
	_ = x[ETH_P_PPP_MP-8]
	_ = x[ETH_P_PPP_SES-34916]
	_ = x[ETH_P_PUP-512]
	_ = x[ETH_P_PUPAT-513]
	_ = x[ETH_P_RARP-32821]
	_ = x[ETH_P_SCA-24583]
	_ = x[ETH_P_SLOW-34825]
	_ = x[ETH_P_SNAP-5]
	_ = x[ETH_P_TEB-25944]
	_ = x[ETH_P_TIPC-35018]
	_ = x[ETH_P_TRAILER-28]
	_ = x[ETH_P_TR_802_2-17]
	_ = x[ETH_P_WAN_PPP-7]
	_ = x[ETH_P_WCCP-34878]
	_ = x[ETH_P_X25-2053]
	_ = x[ETH_P_ATT_PACE-29555]
}

const _EthP_name = "802_3AX25ALL802_2SNAPDDCMPWAN_PPPPPP_MPLOCALTALKCANPPPTALKTR_802_2MOBITEXCONTROLIRDAECONETHDLCARCNETDSATRAILERLOOPPHONETIEEE802154CAIFPUPPUPATIPX25ARPBPQIEEEPUPIEEEPUPATDECDNA_DLDNA_RCDNA_RTLATDIAGCUSTSCATEBATT_PACERARPATALKAARP8021QIPXIPV6PAUSESLOWWCCPMPLS_UCMPLS_MCATMMPOAPPP_DISCPPP_SESLINK_CTLATMFATEPAEAOE8021ADTIPC1588FCOEFIPEDSA"

var _EthP_map = map[EthP]string{
	1:     _EthP_name[0:5],
	2:     _EthP_name[5:9],
	3:     _EthP_name[9:12],
	4:     _EthP_name[12:17],
	5:     _EthP_name[17:21],
	6:     _EthP_name[21:26],
	7:     _EthP_name[26:33],
	8:     _EthP_name[33:39],
	9:     _EthP_name[39:48],
	12:    _EthP_name[48:51],
	16:    _EthP_name[51:58],
	17:    _EthP_name[58:66],
	21:    _EthP_name[66:73],
	22:    _EthP_name[73:80],
	23:    _EthP_name[80:84],
	24:    _EthP_name[84:90],
	25:    _EthP_name[90:94],
	26:    _EthP_name[94:100],
	27:    _EthP_name[100:103],
	28:    _EthP_name[103:110],
	96:    _EthP_name[110:114],
	245:   _EthP_name[114:120],
	246:   _EthP_name[120:130],
	247:   _EthP_name[130:134],
	512:   _EthP_name[134:137],
	513:   _EthP_name[137:142],
	2048:  _EthP_name[142:144],
	2053:  _EthP_name[144:147],
	2054:  _EthP_name[147:150],
	2303:  _EthP_name[150:153],
	2560:  _EthP_name[153:160],
	2561:  _EthP_name[160:169],
	24576: _EthP_name[169:172],
	24577: _EthP_name[172:178],
	24578: _EthP_name[178:184],
	24579: _EthP_name[184:190],
	24580: _EthP_name[190:193],
	24581: _EthP_name[193:197],
	24582: _EthP_name[197:201],
	24583: _EthP_name[201:204],
	25944: _EthP_name[204:207],
	29555: _EthP_name[207:215],
	32821: _EthP_name[215:219],
	32923: _EthP_name[219:224],
	33011: _EthP_name[224:228],
	33024: _EthP_name[228:233],
	33079: _EthP_name[233:236],
	34525: _EthP_name[236:240],
	34824: _EthP_name[240:245],
	34825: _EthP_name[245:249],
	34878: _EthP_name[249:253],
	34887: _EthP_name[253:260],
	34888: _EthP_name[260:267],
	34892: _EthP_name[267:274],
	34915: _EthP_name[274:282],
	34916: _EthP_name[282:289],
	34924: _EthP_name[289:297],
	34948: _EthP_name[297:304],
	34958: _EthP_name[304:307],
	34978: _EthP_name[307:310],
	34984: _EthP_name[310:316],
	35018: _EthP_name[316:320],
	35063: _EthP_name[320:324],
	35078: _EthP_name[324:328],
	35092: _EthP_name[328:331],
	56026: _EthP_name[331:335],
}

func (i EthP) String() string {
	if str, ok := _EthP_map[i]; ok {
		return str
	}
	return "EthP(" + strconv.FormatInt(int64(i), 10) + ")"
}
